# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# the build will trigger on any changes to the master branch
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md;azure-pipelines.yml;LICENSE;.gitignore

# stop 2 build trigger from the submission of the Pull Request so we only get one from the CI merge
pr: none

# the build will run on a Microsoft hosted agent, using the lastest Windows VM Image
pool:
  vmImage: 'windows-latest'

variables:
  configuration: 'Release'
  dotnetSdkVersion: '6.0.x'

steps:
- task: UseDotNet@2
  displayName: 'Use dotnet Core SDk $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Restore sln dependencies'
  inputs:
    command: 'restore'
    projects: 'AgileTea.Persistence.sln'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    arguments: '--no-restore'
    configuration: $(configuration)

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    configuration: $(configuration)
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages'

- task: PublishBuildArtifacts@1
  displayName: publish artifacts
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
